import { Box, Button } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect } from "react";
import useFetch from "../hooks/useFetch";
import Header from "../components/Header/Header";

export default function Home() {
  const { loadedData } = useFetch("https://restcountries.com/v2/name/irn");
  console.log(loadedData);

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </Box>
  );
}
